version: "3.4"

services:
  app:
    build:
      context: .
      target: dev
    environment:
      MONGO_URI: mongodb://bookworm:bookworm@db
    tty: true
    links:
      - db
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
    - .:/opt

  db:
    image: "mongo:4"
    environment:
      MONGO_INITDB_ROOT_USERNAME: bookworm
      MONGO_INITDB_ROOT_PASSWORD: bookworm
