version: "3.4"

services:
  app:
    build:
      context: .
      target: dev
    tty: true
    links:
      - db
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
    - .:/opt

  db:
    image: "mongo:4"
